### ISSUE TITLE
Ανάγνωση δεδομένων από αισθητήρα

### ISSUE THREAD

**Issue by gfour** [maellak/DIYiotSketch#1]
Υλοποίηση και φόρτωση sketch για την ανάγνωση των δεδομένων από έναν αισθητήρα (π.χ. accelerometer, photocell).

Ανάλογα με τον αισθητήρα, πρέπει να επιστρέφονται τιμές που να είναι κατανοητές από τον άνθρωπο. Για παράδειγμα, στο accelerometer, ίσως χρειαστεί calibration στο επίπεδο του λογισμικού.

**Comment by dandrits** [comment]
Το issue έχει μοιραστεί σε όλες τις ομάδες μιας και έχει ανατεθεί σε καθεμία από αυτές η αλλαγή των sketches για κάθενα αισθητήρα

**Comment by dandrits** [comment]
Πλέον έχουν διορθωθεί όλα τα sketces που μας ενδιαφέρουν και έχουν ανατεθεί στις 4 ομάδας.

**Comment by dandrits** [comment]
To accelerometer θα γίνει σε νέο issue!
